# pre-processing
# cosmic ray
remove_cr: True
set_saturation_to_zero: True
kwargs_remove_cr:
  gain: 1.0
  readnoise: 10.0
  sigclip: 3.5
  niter: 10
  cleantype: idw
  satlevel: 60000

# Overall parameters
output_folder: "." # null will save to the same directory as the input

# background subtraction
subtract_background: True
sigma_clip: 3.0
background_estimator: MMM
background_box_size: 51
background_filter_size: 5
background_filename: null # null will append "background" to the input file name
background_subtracted_filename: null # null will append "background_subtracted" to the input file name
save_background_figure: True
save_background_fits: True
background_figsize: [10, 10]
bkg_kwargs: {}

# guess from header
seeing:
pixelscale:
seeing_keyword: ["seeing", "l1seeing", "l1see", "dimmsee", "fwhm", "l1fwhm", "dimmfwhm"]
pixelscale_keyword: ["pixscale", "pixelscl", "pixscl", "arcpix", "arcscpix", "secpix", "aspix"]

# pre- get_good_stars
n_fwhm: 4

# get_good_stars
threshold: None
threshold_snr: 3.0
threshold_sigma_clip: 3.0
fwhm_pix: null # use the seeing value if not given
box_size: null # null to compute from the seeing and pixelscale (This overrides n_fwhm)
minsep_fwhm: 2.0
convolve: True
save_convolved_figure: True
fig_size: [10, 10]
convolved_figure_filename: null
sigma: None
npeaks: 100
stars_tbl: None
edge_size: 15
save_dao_tbl: True
dao_tbl_filename: null
save_stars: True
stars_overwrite: True
stars_filename: "good_stars"
save_stars_tbl: True
stars_tbl_overwrite: True
stars_tbl_filename: "good_stars_tbl"
get_good_stars_kwargs:
  brightest: 100
  peakmax: 55000

# build_psf
oversampling: 2
return_oversampled: False
create_figure: True
save_figure: True
stamps_nrows: None
stamps_ncols: None
figsize: [10, 10]
stamps_figname: "PSF_stamps"
psf_figname: "PSF"
save_psf_model: True
model_overwrite: True
model_filename: "epsf_model"
save_center_list: True
center_list_overwrite: True
center_list_filename: "epsf_center_list"
build_psf_kwargs:
  num_iteration: 100
  n_recenter: 25
  saturation_limit: 55000
  kwargs_psf_stacking:
    stacking_option: median